on: [workflow_dispatch]

name: Build & upload release artifacts
jobs:
  create-release:
    name: build macos, ios, android
    runs-on: macos-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup java
        uses: actions/setup-java@v2
        with:
          java-version: '15'
          distribution: 'adopt'
      - name: setup flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: install dependencies
        run: flutter pub get
      - run: flutter build apk --release --split-per-abi
      - run: |
          flutter build ios --release --no-codesign
          cd build/ios/iphoneos
          mkdir Payload
          cd Payload
          ln -s ../Runner.app
          cd ..
          zip -r app.ipa Payload
      - run: flutter build macos --release
      - name: Upload Mac artifacts
        uses: actions/upload-artifact@v3
        with: 
          name: macos-artifacts
          path: |
            build/app/outputs/apk/release/*.apk
            build/ios/iphoneos/app.ipa
            build/macos/Build/Products/Release/*.app
