on: [workflow_dispatch]

name: Build & upload release artifacts
jobs:
  create-release-mac:
    name: build macos, ios, android
    runs-on: macos-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup java
        uses: actions/setup-java@v2
        with:
          java-version: '15'
          distribution: 'adopt'
      - name: setup flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: install dependencies
        run: flutter pub get
      # - run: |
      #   "flutter create ."
      #   flutter build macos --release
      - run: flutter build apk --release --split-per-abi
      - run: |
          flutter build ios --release --no-codesign
          cd build/ios/iphoneos
          mkdir Payload
          cd Payload
          ln -s ../Runner.app
          cd ..
          zip -r app.ipa Payload
      - name: Upload Mac artifacts
        uses: actions/upload-artifact@v3
        with: 
          name: macos-artifacts
          path: |
            build/app/outputs/apk/release/*.apk
            build/ios/iphoneos/app.ipa
            build/macos/Build/Products/Release/*.app
  create-release-win:
    name: build windows
    runs-on: windows-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: install dependencies
        run: flutter pub get
      - run: flutter build windows --release
      - name: Upload Windows artifacts
        uses: actions/upload-artifact@v3
        with: 
          name: windows-artifacts
          path: |
            build/windows/runner/Release
  create-release-linux:
    name: build linux
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      # https://docs.flutter.dev/development/platform-integration/linux/building
      - name: setup system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libgtk-3-0 libblkid1 liblzma5
      - name: setup flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: install dependencies
        run: flutter pub get
      - run: flutter build linux --release
      - name: Upload Linux artifacts
        uses: actions/upload-artifact@v3
        with: 
          name: linux-artifacts
          path: |
            build/linux/release/bundle
